### ISSUE TITLE
Design volcano structure

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#167] opened 2019-02-13 22:33 UTC
Th structure of the volcano needs to be designed.

The volcano is covered in the rules and will be covered with carpet on the top and sides.
In addition the volcano will ideal hold some effects unit for after the finals.

**Comment by kierdavis** [comment] 2019-02-14 07:41
Is this a duplicate of #105?

**Comment by WillB97** [comment] 2019-02-14 12:48
This can almost be made using 4 pieces of SUSU 8x4 light deck.
However 12ft is 3657.6mm which is outside the current tolerance.

In future years arena items should be sized to make best use of standard sized equipment

**Comment by Tyler-Ward** [comment] 2019-02-14 13:11
We considered making or of deck when designing the game however the stage deck was considered to high for the robots so using deck was discounted, I thought it was still 8x4 but that must have been changed at some point when the rules were being refined.

**Comment by WillB97** [comment] 2019-02-14 13:22
Is there a planned height for the raised section. I don't see anything stated in rules.

**Comment by Tyler-Ward** [comment] 2019-02-14 13:45
from rules 1.7. The volcano (and, notably, not the caldera) is elevated from the floor
by 75mm ± 5mm.

**Comment by WillB97** [comment] 2019-02-14 14:21
A possible solution maybe 18mm plywood with a 2x2in frame and carpet on the top

**Comment by Tyler-Ward** [comment] 2019-02-14 15:47
That sounds like it would be a good solution, are you able to come up with a design and work out what materials we would need to buy to build it.

**Comment by RealOrangeOne** [comment] 2019-02-14 20:56
The caldera needs to support 2 days of teams standing on them, and likely a fair amount of robot abuse, as many teams look to just be driving at the edge and hoping they jump over it. I believe the idea of using insulation board was thrown around, which could work well, however we'd want to ensure the edges are much harder (eg a wooden frame)

**Comment by PeterJCLaw** [comment] 2019-02-15 09:38
> Is this a duplicate of #105?

I think it's fine to have this as a sub-task, the other part being the tokens.

**Comment by WillB97** [comment] 2019-02-18 13:18
The plywood design comes to £38 per board

| Item | Quantity | Cost |
| --- | --- | --- |
| [12mm Softwood Plywood](https://www.wickes.co.uk/Wickes-Structural-Softwood-Plywood-CE2%2B---12mm-x-1220mm-x-2440mm/p/183450) | 1 | £27.00 |
| [2.5x1.5in Plywood Timber 2400mm](https://www.wickes.co.uk/Wickes-Studwork-CLS-Timber---38mm-x-63mm-x-2400mm/p/107177) | 4 |  £11.00 |
| Total || £38.00 |

**Comment by PeterJCLaw** [comment] 2019-02-19 23:20
@WillB97 thanks for putting that together, do you have some plans somewhere for what the build would look like?
Related questions:
* would it be safe to stand on?
* how much time/effort would that take to build?

Our original intention (and the design which the rules are actually written based upon) was to use overlapping sheets of insulation foam for the bulk. They're available in 1200 x 2400 sheets, so we'd planned to get 8 of them and butt them together in two layers like this (though with the top layer having the inverse offset):

![image](https://user-images.githubusercontent.com/336212/53054620-d6839180-349c-11e9-807b-cadf1d146ed1.png)

**Comment by PeterJCLaw** [comment] 2019-02-19 23:27
> The volcano .. will be covered with carpet on the .. sides.

Huh, when did that happen? I'd thought we were going for hardboard on the sides so that ultrasound would bounce off it.

> In addition the volcano will ideal hold some effects unit for after the finals.

I'm not sure this is going to be practical, especially given the likely beating the structure is going to take if teams are going for ramming based approaches.

**Comment by Tyler-Ward** [comment] 2019-02-19 23:44
> > The volcano .. will be covered with carpet on the .. sides.
> 
> Huh, when did that happen? I'd thought we were going for hardboard on the sides so that ultrasound would bounce off it.

I thought that was the plan from the core team meeting discussion. hardboard could also work but we would need some edging strip or similar on the top otherwise i expect it will get broken quite quickly.

> > In addition the volcano will ideal hold some effects unit for after the finals.
> 
> I'm not sure this is going to be practical, especially given the likely beating the structure is going to take if teams are going for ramming based approaches.

This is optional if we can find a good way to do it these will be in the inside at the corners anyway so should be more protected from bumps than the rest of the walls.

**Comment by WillB97** [comment] 2019-02-19 23:50
The plan with plywood would be a timber outer frame with timbers on the narrow edge for height.
Two cross braces for support and 12mm plywood as a top (see diagram).
This should support up to about 150kg point load and best part of a tonne distributed.

. | . | .
--- | --- | ---

I have a friend who is willing to construct them and would only take a day or so when he's available.

**Comment by WillB97** [comment] 2019-02-20 00:02
> > The volcano .. will be covered with carpet on the .. sides.
> 
> Huh, when did that happen? I'd thought we were going for hardboard on the sides so that ultrasound would bounce off it.
> 
If they are going to be carpeted at all I would recommend carpeting both the top and sides as any edge on the visible surface will likely be pulled up by robots ramming it.

I don't know how detrimental it would be to the ultrasound as, if it's the same type of carpet used at the smallpeice event, it should be quite thin and tight weave. Although we should test out it's effect.
> > In addition the volcano will ideal hold some effects unit for after the finals.
> 
> I'm not sure this is going to be practical, especially given the likely beating the structure is going to take if teams are going for ramming based approaches.

While it would probably be possible to fit confetti under the raise confetti generally travels in the direction the tube is pointed so would travel across the floor not upward.
Also as the volcano is an island I'm not convinced about using a wireless device, which cannot be easily and reliably triggered, or disarmed in the event of emergency action, to fire what is essentially a pyrotechnic.

**Comment by PeterJCLaw** [comment] 2019-02-23 12:01
> Two cross braces for support and 12mm plywood as a top (see diagram).

@WillB97 your diagram doesn't seem to have made it to GitHub, could you re-post it?

**Comment by WillB97** [comment] 2019-02-23 12:15
Consider the table a diagram.

Essentially the 8x4 area is divided equally into 3 rectangles of about 2.6x4ft.

**Comment by RealOrangeOne** [comment] 2019-03-01 13:25
Upgrading status as this has a slightly high lead time, and would be ideal to get done before the next tech day.

**Comment by RealOrangeOne** [comment] 2019-03-02 10:47
This has now been designed by @WillB97, and the parts ordered.

**Closed by RealOrangeOne** 2019-03-02 10:47 UTC
Labels: must have, urgent

**Comment by PeterJCLaw** [comment] 2019-03-02 11:09
@WillB97 ah, I see. Just to check: you'd then have four of those 8'×4' blocks arranged somewhat like the diagram I drew?

Thinking this through further: how do we ensure that each of those blocks:
* stayed put?
* was attached to each of the other pieces?

I suspect that we can solve the first by putting velcro on the bottom of the blocks. If that's enough then most likely we don't need to solve the second one directly as the blocks will be fairly immovable.

The remaining question is whether we can have suitable mock-ups of this at the upcoming Tech Days next week (9th March). I suspect that a full size 8'×4' block is going to be far too large to transport to London, though _might_ be viable at Southampton.
Is there something equivalent we could have built for London?

**Comment by WillB97** [comment] 2019-03-02 17:17
I think it would be better to bolt all the blocks to together and sheer weight should keep it in place.

It's likely that they will be made in time for the tech day but there isn't any spare material to make a smaller equivalent for London.

**Comment by PeterJCLaw** [comment] 2019-03-02 17:26
For context: some of the teams appear to be planning to mount the volcano by driving at it and having an inverse ramp on the front of their robots.
