### ISSUE TITLE
Acquire tape for the SR2022 arenas

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#807] opened 2022-01-27 16:21 UTC
For the competition we will need vast quantities of tape: - white - black - neon yellow, blue, green, pink - hazard - double-sided for laying the carpet with
We should check what stocks we have and order more if needed.

### Original

[comp/arena/tape](https://github.com/srobo/recurring-tasks/blob/master/comp/arena/tape.yaml)

### Dependencies

 * #734 Pre competition storage trip

**Comment by RealOrangeOne** [comment] 2022-02-03 20:45
Current stock in the container:

- ~13 rolls of black gaff
- 1 role of Orange, Pink and Yellow gaff
- 2 roles of Green gaff
- 1 roll of white gaff
- Huge amount of carpet and masking tape
- ~4 rolls of electrical tape, misc colours

**Comment by WillB97** [comment] 2022-02-10 23:22
- We'll need at least 2 full roles of NEC floor tape.
- How full are the rolls of coloured gaff? Since they are explictly used for team colour markings in the arena we need to make sure we have sufficient.
- We'll likely need some more white gaff, especially if we decide to tape the joins in the arena.
- 4 rolls of electrical tape is very little, we'll definately need more of that

Certainly looks like we're going to need a tape order, a good supplier is https://www.10outof10.co.uk/acatalog/gaffer_tape.html

**Comment by sedders123** [comment] 2022-02-10 23:57
We have used https://www.gaffatape.com/ in the past as another potential supplier

**Comment by RealOrangeOne** [comment] 2022-02-11 17:22
Next container trip we can definitely get more accurate values for this. Given the lead time on tape it's not too much of a concern at this stage.

> We'll need at least 2 full roles of NEC floor tape.

That's in there. I'd say there's probably 4-5 total.

> How full are the rolls of coloured gaff?

This is counting them as "full" roles. I think all the colours either had brand new rolls, or multiple rolls.

**Comment by WillB97** [comment] 2022-03-05 17:18
We also need to purchase 25mm tape for the cans.

**Comment by Scarzy** [comment] 2022-04-05 21:08
Is this the only use for tape that's been accounted for?

I believe we have historically also used tape for holding down loose cables and putting team labels onto hi-viz jackets

**Comment by RealOrangeOne** [comment] 2022-04-08 19:02
Here's what we have:

<details>

![IMG_20220408_164118](https://user-images.githubusercontent.com/6527489/162501117-494b7559-b25d-4ec0-8011-781456dd7121.jpg)

</details>

More specifically:

<details>
<summary>Quite a lot of electrical tape</summary>

![IMG_20220408_164205](https://user-images.githubusercontent.com/6527489/162504096-8b0eb509-fa62-45d9-80df-3e8853d8c81f.jpg)

</details>


<details>
<summary>Not a huge amount of coloured tape. Might be worth getting another roll of each?</summary>

![IMG_20220408_164243](https://user-images.githubusercontent.com/6527489/162506112-44db0bf4-d453-45f8-9b3d-ffcdaac8bea5.jpg)

</details>

<details>
<summary>Plenty of black gaff</summary>

![IMG_20220408_164432](https://user-images.githubusercontent.com/6527489/162506909-0804f447-16f4-4b98-b2ac-3c42761a5bff.jpg)


</details>

<details>
<summary>Ample carpet tape (NEC approved)</summary>

![IMG_20220408_164455](https://user-images.githubusercontent.com/6527489/162507288-c03eabae-3806-46db-af7b-8ec48425dd2d.jpg)

</details>

Also notable:

- Hazard tape, if and when we need it
- Some masking tape and clear tape
- A decent amount of white gaff
- Silver gaff, on the off chance we need that

**Comment by Tyler-Ward** [comment] 2022-04-08 21:33
With regards to the NEC floor tape, if this is still the stuff from newbury it should be noted that it disentegrates rather than coming up off the floor

**Comment by PeterJCLaw** [comment] 2022-04-08 22:06
> Not a huge amount of coloured tape. Might be worth getting another roll of each?

Is the fifth pile (far right) actually a different colour or was that a lighting weirdness? It looks like it's the pink?

Do we actually need much of the coloured tapes?
My recollection is that we use it exclusively for marking in the arena and making flags. Some guesses on how much that needs follow.

Arena corner (8m):
- 3.5m mark scoring zone (2.5m × √2)
- 4.5m zone number (3 × 1.5m each; likely an overestimate)

Flags (2m):
- 1m : 0.15m long × 3 lengths × 2 sides
- × 2 flags per corner

Staging desks (3.5m)
- 2m to mark either side of each slot (assuming 1m wide tables; we could probably halve the tape along its length if needed, that may also look better)
- 1.5m for the zone number

That's 14m per corner, per arena, so call it 30m overall. Have I missed anywhere that we use the coloured tape?

I suspect we could easily scale back the amount used in the test arena quite a bit (just one zone number for example).

Those rolls are I think 50m each? If so I think we're fine for all but yellow. Depending on how much budget we have and whether delivery is expensive I'm not sure we need to get more of the others.

**Comment by PeterJCLaw** [comment] 2022-04-08 22:07
Two things for certain - we should:
- work out how big the rolls are and record that somewhere
- try to use up the shorter rolls at the competition (it's easier to store and account for whole rolls)

**Comment by RealOrangeOne** [comment] 2022-04-08 22:20
> Is the fifth pile (far right) actually a different colour or was that a lighting weirdness?

Yes - It's red. Not sure what we have it for, but is perhaps useful for something.

> Do we actually need much of the coloured tapes?

We might. We often find it useful to mark things with the zone colours (eg staging tables), and not running out of tape would be great. Yellow is definitely the one which concerns me the most, with pink not too far behind. We definitely have enough green and orange, though. 

> NEC floor tape

I thought this was from SR2019, but this feels like a large amount for just 1 year. Yes the tape probably does degrade, but it should be ok. It was the masking tape which was the most horrible on the Newbury floors. We'll just have to be careful and keep an eye on it as we lay / pull it up.

**Comment by PeterJCLaw** [comment] 2022-04-08 22:29
> > Is the fifth pile (far right) actually a different colour or was that a lighting weirdness?
> 
> Yes - It's red. Not sure what we have it for, but is perhaps useful for something.

Ah, yeah. I recall there being some red now you mention it. I think it was used in prop construction one year ... which maybe suggests a use for it this year too?

> > Do we actually need much of the coloured tapes?
> 
> We might. We often find it useful to mark things with the zone colours (eg staging tables)

Yeah, I accounted for the staging tables/desks.

I think we have in the past used those colours for things other than zone (or zone-equivalent) markings and I think we need to be mindful to not do that. Partly as it's quite expensive stuff, though also to keep the arena somewhat special.

**Comment by PeterJCLaw** [comment] 2022-04-08 22:38
Ok, based on https://github.com/srobo/tasks/issues/907#issuecomment-1093416618 we think the rolls are 22m.
Given that we need 22m of each that's a bit close for my liking on yellow, so we definitely need more of that. Pink looks too close to call too, so we should get more of that. Green & orange have two full (or nearly so) rolls so I think we're good for those.

**Comment by RealOrangeOne** [comment] 2022-04-09 10:44
Because we **need** to attach markers to the arena using white tape (so there's enough contrast, we should probably purchase some more of that, too.

**Comment by PeterJCLaw** [comment] 2022-04-09 19:41
A rough estimate of the white tape for the arena markers is 28m (4 sides at 0.25m each, 28 markers), plus spare for repairs, say 30m?
We maybe don't need full width tape? Might be safest to use that though.
It looks like we've got a couple of half-used rolls there plus another full one (though that roll looks like it's not great given that it's creased), so maybe a single roll more would be enough?

**Comment by PeterJCLaw** [comment] 2022-04-09 19:41
@WillB97 I think you mentioned earlier today that you were doing a tape order -- can we assign this to you?

**Comment by WillB97** [comment] 2022-04-09 19:45
> A rough estimate of the white tape for the arena markers is 28m (4 sides at 0.25m each, 28 markers), plus spare for repairs, say 30m? We maybe don't need full width tape? Might be safest to use that though. It looks like we've got a couple of half-used rolls there plus another full one (though that roll looks like it's not great given that it's creased), so maybe a single roll more would be enough?

Note we have markers in both arenas so 56m.

**Comment by WillB97** [comment] 2022-04-09 22:53
The important thing about NEC floor tape is there are high-tack and low-tack sides marked on the tape, high-tack __must__ be stuck to the carpet not the floor.

We also need 18m of gaffa tape for hi-viz, a light colour.

For marking the cans we need ~15m of 1 inch tape, this should provide a good contrast. We have some partial coloured rolls but for fairness all cans need to be marked with the same colour.

As for tape quantities
- Looks like we have sufficient carpet tape
- We have sufficient black electrical tape for most cabling around the arena
- For coloured gaff: 1 roll of yellow and 1 roll of pink gives us a comfortable amount
- Another 2 rolls of white electrical tape would be useful, particularly for taping team labels to pit tables.
- A roll of blue gaff for taping the carpet join is needed
- We probably have sufficient white gaff although of questionable quality
- We could get a roll of 1 inch black electrical tape for £1.38 then there isn't an unknown about tape lengths

From [10outof10](https://www.10outof10.co.uk/acatalog/gaffer_tape.html) this works out to:
- 1 flourescent yellow 50m (£11.27)
- 1 flourescent pink 50m (£11.27)
- 2 white electrical 33m (£1.80)
- 1 flourescent blue 50m (£11.27)
- 1 black 1-inch electrical 33m (£1.38)
- postage (£9.00)

- Optionally 1 white gaffa 50m (£8.58)

@Adimote Without white gaffa it comes to £45.98 which is within the budget line.

**Comment by RealOrangeOne** [comment] 2022-04-10 14:23
IMO we should get some additional white gaff, _just_ in case. 

> Another 2 rolls of white electrical tape would be useful, particularly for taping team labels to pit tables.

Really? We have tonnes of electrical tape, and I don't think for this usage we need to be consistent with the colour

Other than that, the above list also sounds right to me :+1:

**Comment by WillB97** [comment] 2022-04-10 15:22
Swapping the white tape for gaff makes it £52.76 but since we aren't buying carpet tape this is still less than the total allocated to buy tape.

**Comment by Adimote** [comment] 2022-04-11 21:49
Sounds good to me!

**Comment by WillB97** [comment] 2022-04-12 08:17
This has been ordered, @Adimote can you close this when it arrives.

**Comment by Adimote** [comment] 2022-04-13 19:59
Confirmed arrived :)

**Closed by Adimote** 2022-04-13 19:59 UTC
Labels: I: Should Have, S: In Progress, A: Arena, Long lead time, A: Logistics
