### ISSUE TITLE
Competition Network Topology Planning

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#69] opened 2019-02-13 17:42 UTC
We need to work out what we need in the competition network, what services we want to run, etc.

Includes:
- SRComp
- Display Screens
- ~Telephony (probably)~
- NOT Competitor WiFi (see #68)

Layer 2 only is apparently a good idea, but this will require our own cabling everywhere (which we should be doing anyway).

### SRComp stuff

Hardwire is essential, WiFi very much a nice-to-have.

Everything wants to have DHCP issued addresses for ease of setup, though some of the addresses should be fixed in config.
Everything here needs to be able to establish and maintain communications with everything else (there's a subset of this which is actually the strict requirement -- the screens don't need to be able to talk to each other, but it very nearly amounts to the same thing).

This consists of:
- the compbox, which _MUST HAVE_ a fixed IP and _MAY HAVE_ a DNS entry (`compbox-2019`)
- the screen drivers (Pis), which _MUST HAVE_ fixed IPs (ideally arranged such that their identifying number in the inventory maps directly into their IP, for example Pi number 3 being `x.x.x.103`, mostly for ease of debugging) and _MAY HAVE_ DNS entries
- four or so volunteer machines

Protocols which _MUST_ work (inwards, outwards and internally):
* SSH
* HTTP and HTTPS
* `git://`
* NTP
* ICMP (`ping`)

Whatever is hosting the network _MUST NOT_ assume that it has complete control over the physical topology. Being able to add a switch where we realise we need it, either to extend cables or for diagnostic access is important. Similarly, deciding that we're going to bridge other stuff into the network has been important (though hopefully we'd do that in concert with the host situation rather than against it).

*Note on the screens*

The screens around the venue need to be able to talk to _a_ compbox like machine. Ideally that would be the in-venue one, over an in-venue-only link. There is no need for this link to be particularly secure as it is conveying public information. A fallback of using a public compbox (which would be secure as it would have TLS) is an option.

**Comment by WillB97** [comment] 2019-02-14 13:25
Is this network going to require an internet uplink and is there a plan of how this would be achieved.

**Comment by Tyler-Ward** [comment] 2019-02-14 13:46
We will need an uplink, typically this has been an isoloutions port from the lighting booth.

**Comment by PeterJCLaw** [comment] 2019-02-15 09:32
This doesn't strictly need an uplink, though it's definitely _much_ easier if we have one.

**Comment by PeterJCLaw** [comment] 2019-02-16 15:33
If we can do effectively the same as we did for Smallpeice (connecting segments of our own network using the existing infrastructure) I think that that would be ideal, not least as it would avoid us needing to run too much additional cabling through the venue.

I forget exactly whose kit we borrowed that time, but if we could borrow that again it would be handy.
Alternatively we could probably hire some networking equipment.

**Comment by trickeydan** [comment] 2019-03-05 12:16
This has got much easier now that we're not doing #71. I don't think we'll need much beyond the cube and tech deck. I suggest using [Wireguard](https://www.wireguard.com/) as a VPN due to the ease of setup compared to the technical expertise that was required last year for the IPSec.

**Comment by RealOrangeOne** [comment] 2019-03-05 13:54
What part of our stack needs a VPN? We're not trying to securely bridge 2 networks. The arena will be hard-wired to the ops desk, and the screens can be driven by a public version of `srcomp-http`, right?

**Comment by trickeydan** [comment] 2019-03-05 16:18
> What part of our stack needs a VPN? We're not trying to securely bridge 2 networks. The arena will be hard-wired to the ops desk, and the screens can be driven by a public version of `srcomp-http`, right?

What if the internet connection goes down? We need to use internal networks and traverse the LANs, much like we did at Smallpeice 2018

**Comment by Tyler-Ward** [comment] 2019-03-05 16:24
The score entry desk will be in a different area to the rest of the kit so will need a VPN to talk to the comp-box directly.

**Comment by WillB97** [comment] 2019-03-05 16:31
The score entry can be hard wired through the installed ethernet ties. I agree with @RealOrangeOne, as the only system accessed over the VPN would be the display endpoint this could be port forwarded through the compbox and directly accessed across the isolutions network

**Comment by trickeydan** [comment] 2019-03-05 16:33
> directly accessed across the isolutions network

this assumes that their firewalls don't get in the way. We had to have a VPN for smallpeice

**Comment by WillB97** [comment] 2019-03-05 17:05
If you can't access http between them you won't be able to vpn between them.

**Comment by trickeydan** [comment] 2019-03-05 17:24
> If you can't access http between them you won't be able to vpn between them.

Not true. http traffic may only be traversable in the wrong direction. E.g compbox can reach screen

**Comment by RealOrangeOne** [comment] 2019-03-05 17:29
I suggest we try at all costs _not_ to ship a VPN, and only ship one if we actually have to. It's likely another piece to go wrong, and we can probably function without it. 

That being said, if we _do_ need a VPN, and we can make it do what we need to, my vote does go to WireGuard, although I don't think that's worth discussing here until the day when we realise we actually need one.

**Comment by trickeydan** [comment] 2019-03-05 17:57
The best way to resolve this ticket is to send a volunteer around with an ethernet cable. Any takers? I might be able to do it next week.

**Comment by PeterJCLaw** [comment] 2019-03-06 23:32
> The arena will be hard-wired to the ops desk,

Definitely, this is pretty essential for ensuring smooth running.

> and the screens can be driven by a public version of `srcomp-http`, right?

Hrm, I'd not thought about this. For things outside the arena we certainly _could_ do this, though it would be nicer to keep it all local.
I doubt however that we would lose internet but still have local (Uni) networking (more likely it's all or nothing).

> VPNs

I think there's bit of confusion here. I'm not aware that we've ever run a VPN in the strictest sense, certainly not something involving an external provider and in any case that would also be susceptible to an upstream failure, so doesn't solve the problem of internet loss. I don't see any benefit whatsoever to running this sort of VPN.

However, we did previously do some fancy routing between a pair of routers, enabling them to share routes. I would suggest we aim to replicate that as it avoids needing either long-range WiFi or needing to run our own cabling.

The unknown is which ports this will work with. Unfortunately, I don't think that we can determine this without actually setting it up (or at least having things plugged in at both ends).

The main complication here is that we previously set this up with only two ends, where now we're looking (#99) at having several more than that. As a result of that, having the non-Cube screens running off a public host is likely easiest (and definitely worth considering as a fallback).
I'd like to try to make local networking work first though. I'll see if I can dig out the instructions we created for the route-sharing setup.

**Comment by PeterJCLaw** [comment] 2019-03-06 23:34
> The score entry desk will be in a different area to the rest of the kit

Why are we doing this? Usually they're sat on the same desk which has the compbox on it.

**Comment by RealOrangeOne** [comment] 2019-03-07 07:15
> > The score entry desk will be in a different area to the rest of the kit
> 
> Why are we doing this? Usually they're sat on the same desk which has the compbox on it.

We trialed this at Smallpeice 2018 and it worked well. With scoring on the cube floor, the scoring sheets can get to the scorer much faster, and it clears some space on the balcony desk, which is probably a good thing.

**Comment by trickeydan** [comment] 2019-03-07 11:44
> > The score entry desk will be in a different area to the rest of the kit
> 
> Why are we doing this? Usually they're sat on the same desk which has the compbox on it.

We trialed this at Smallpeice 2018. It resulted in less logistics of having to get the sheets upstairs, and faster uploading of the scores.

If there is a _significant_ advantage to the scoring being on the balcony, I'd be interested to hear it.

**Comment by trickeydan** [comment] 2019-03-07 11:47
> However, we did previously do some fancy routing between a pair of routers, enabling them to share routes. I would suggest we aim to replicate that as it avoids needing either long-range WiFi or needing to run our own cabling.

I believe that this was an IPSec setup, i.e a VPN. 


> The main complication here is that we previously set this up with only two ends, where now we're looking (#99) at having several more than that. As a result of that, having the non-Cube screens running off a public host is likely easiest (and definitely worth considering as a fallback).
> I'd like to try to make local networking work first though. I'll see if I can dig out the instructions we created for the route-sharing setup.

A local (non-external) VPN solution also works here and I think a solution such as Wireguard is significantly easier to configure than routing. Especially given the restrictions of the iSol network.

**Comment by trickeydan** [comment] 2019-03-07 22:44
We have had a volunteer and his IT company offer to provide equipment and setup the entire network. 

If we wish to do this with him, we need to get a spec of all of the ports and their locations by __tomorrow evening__. He would like a specification so that he knows what he needs before setup.

**Comment by PeterJCLaw** [comment] 2019-03-07 22:49
> > > The score entry desk will be in a different area to the rest of the kit
> > 
> > Why are we doing this? Usually they're sat on the same desk which has the compbox on it.
> 
> We trialed this at Smallpeice 2018 and it worked well. With scoring on the cube floor, the scoring sheets can get to the scorer much faster, and it clears some space on the balcony desk, which is probably a good thing.

Interesting. We'd definitely found in the past that the score-entry and judging desks needed to be somewhere that was isolated from competitors and somewhat isolated form noise. If we can achieve that somewhere closer to the arena, then all's well.

Note that of course if they're near the arena then they're well in range to just take a network cable direct, via the arena structure. (which leaves me confused about the original comment about them being somewhere else, but oh well)

**Comment by PeterJCLaw** [comment] 2019-03-07 22:55
I'm going to brain-dump some notes about the SRComp aspect of this, but into the description so they're easy to find.

**Comment by PeterJCLaw** [comment] 2019-03-07 23:17
Who's router thingys did we borrow in the past? I'd be up for just going with that solution again as we know it works. Particularly if we can get a few more of those boxes and connect everything that way.

It also occurred to me that in theory we ought to be able to apply the config we applied to those directly to the Pis and avoid needing the middle boxes (though I'm less sure about that)

**Comment by trickeydan** [comment] 2019-03-08 12:40
> Who's router thingys did we borrow in the past?

They belonged to SOWN.

I would suggest going with the Volunteer who has offered to do it all. He has knowledge of undocumented cat5 that was put in place for previous competitions and doesn't intend to do _any_ routing nonsense.

**Comment by WillB97** [comment] 2019-03-08 14:26
> He has knowledge of undocumented cat5 that was put in place for previous competitions

Is this cabling installed in SUSU or additional cable to be run during the setup.

**Comment by trickeydan** [comment] 2019-03-08 14:28
> Is this cabling installed in SUSU or additional cable to be run during the setup.

Installed in SUSU. Apparently by himself some years ago but is not known about by many. e.g apparently there is a run from Tech Deck to Cafe.

**Comment by WillB97** [comment] 2019-03-08 14:42
Last year SUSU upgraded their network audio and a large amount of the networking was rerun so it would be worth checking this still exists.

**Comment by Tyler-Ward** [comment] 2019-03-08 19:20
This is a list of what we need in different parts of the building
https://hackmd.io/rLCNPLVwRq2ibOe3-VZpBQ

**Comment by trickeydan** [comment] 2019-03-09 12:29
We need to send this off by the end of the day.

**Comment by trickeydan** [comment] 2019-03-10 18:37
Sent to Chris. I think we're safe to close this ticket now.

**Comment by RealOrangeOne** [comment] 2019-03-10 18:53
Until a plan is confirmed, we shouldn't close the ticket. We should also enure that that Chris comes back with is appropriate and reasonable for what we're trying to achieve.

**Comment by trickeydan** [comment] 2019-03-10 18:54
> Until a plan is confirmed, we shouldn't close the ticket. We should also enure that that Chris comes back with is appropriate and reasonable for what we're trying to achieve.

You are aware that we are specifying to Chris? He is planning to do exactly as we tell him, as long as he thinks it will work.

**Comment by trickeydan** [comment] 2019-03-16 19:56
The topology has now been confirmed with Chris.

**Closed by trickeydan** 2019-03-16 19:56 UTC
Labels: must have

**Comment by WillB97** [comment] 2019-03-17 23:11
What is this topology that has been agreed on, I have seen mentions elsewhere of a 5GHz radio link but there are no details of this in the hackmd.

**Comment by trickeydan** [comment] 2019-03-17 23:59
> What is this topology that has been agreed on, I have seen mentions elsewhere of a 5GHz radio link but there are no details of this in the hackmd.

It's floating around partially in an email thread, and on paper. The hackmd was the specification.
