### ISSUE TITLE
Sort out sound system for the competition

### ISSUE THREAD

**Issue by RealOrangeOne** [srobo/tasks#980] opened 2023-02-10 11:05 UTC
Speakers and wireless microphones for the judges are required.

### Original

[comp/venue/sound](https://github.com/srobo/recurring-tasks/blob/master/comp/venue/sound.yaml)

### Dependencies

 * #979 Get PRS/PPL: TheMusicLicense for the competition

**Comment by Tyler-Ward** [comment] 2023-02-10 19:07
This appears to be a duplicate of #981

**Closed** 2023-02-10 23:04 UTC
Labels: I: Should Have, AO: Event Logistics
