### ISSUE TITLE
Ship SR2020 kits to Teams not attending Kickstarts

### ISSUE THREAD

**Issue by PeterJCLaw** [srobo/tasks#343] opened 2019-09-08 20:44 UTC
Teams unable to make it to a Kickstart need their kits couriering to them.
Costs for this have historically been covered by SR.
We require teams to explicitly confirm their address by email before dispatching a kit.

### Original

[kickstart/kit/ship-courier](https://github.com/srobo/recurring-tasks/blob/master/kickstart/kit/ship-courier.yaml)

### Dependencies

 * #325 Allocate SR2020 kits to teams

**Comment by PeterJCLaw** [comment] 2019-10-18 18:10
@antoinepetty is looking into what courier services we can use for this. Likely collection would be from either @PeterJCLaw or @RealOrangeOne.

**Comment by antoinepetty** [comment] 2019-10-18 20:06
UPS is looking the most likely
UK: £24.35
Germany: £35.75
India: £67.79

Is this the sort of pricing we had in mind?

**Comment by PeterJCLaw** [comment] 2019-10-19 11:38
Should add: I think we also have a team in Guernsey.

**Comment by RealOrangeOne** [comment] 2019-10-19 12:09
> I think we also have a team in Guernsey
This is correct.

**Comment by antoinepetty** [comment] 2019-10-20 10:57
Sending to Guernsey with UPS would be £40.79 it seems

**Comment by antoinepetty** [comment] 2019-10-20 11:05
So with UPS I believe they have you print a label, but you need to pay upfront rather than via invoice.

**Comment by RealOrangeOne** [comment] 2019-10-20 20:02
@antoinepetty what kind of preparation needs to be done to a RUB to make them shippable? I assume we need to pack out the insides, and print off a label. Anything else?

**Comment by antoinepetty** [comment] 2019-10-21 18:58
I can't find much info about this. The above prices are including the "additional handling" fee for anything not in a cardboard box. I'm thinking we should stretch wrap them as we have done in the past to ensure they don't get opened accidentally in transit.

**Comment by RealOrangeOne** [comment] 2019-10-21 19:14
This is now blocked on https://github.com/srobo/team-emails/pull/31, as we need to prompt to get their confirmed address before dispatching kits!

**Comment by kierdavis** [comment] 2019-10-27 15:12
> what kind of preparation needs to be done to a RUB to make them shippable? I assume we need to pack out the insides, and print off a label. Anything else?

These docs might be useful here: https://srobo.github.io/runbook/kit/logistics/transport/packaging/

Using shrink wrap instead the big mailing bag recommended by these docs should be fine too.

**Comment by RealOrangeOne** [comment] 2019-11-02 12:56
Update on shipping kits to teams:
- An email will go out next week prompting teams to send in disclaimer forms / confirm addresses (https://github.com/srobo/team-emails/pull/32)
- I'll process the responses
- Once a team has signed a form and confirmed their address, i'll pass the address of the team to @rgilton, who will dispatch a kit

**Comment by RealOrangeOne** [comment] 2019-11-13 22:03
Said email went out, so teams have been sending in confirmation of addresses and signed disclaimers. 

There's a delay (hopefully resolved now) in sending out kits due to battery issues. Hopefully the first batch will go out soon.

Some kits are still with me, which will need transferring to someone with capacity to prepare and dispatch them.

**Comment by RealOrangeOne** [comment] 2019-11-15 08:14
@rgilton hopes to send out kits for those who have already responded on Monday.

Currently awaiting the information of 5 teams, which i'll chase next week.

**Comment by RealOrangeOne** [comment] 2019-11-17 11:29
> "spoke too soon.  The courier I thought would do it won't"
> @rgilton, Friday

**Comment by RealOrangeOne** [comment] 2019-12-05 13:23
@rgilton:
> the solution to this problem that we have arrived at is that we are going
to purchase some new batteries that do come with some documentation stating that
they are compliant with regs.
> I will purchase the batteries for the kits that I have in my office now.

There's still some kits at my house, which I won't have time to package and prepare myself, so i'm working on that.

**Comment by RealOrangeOne** [comment] 2019-12-16 19:10
1 kit has been dispatched, with a further 4 to be picked up tomorrow morning.

There's a further 1 which needs to be dealt with, but the rest we haven't heard from, so will need chasing.

**Comment by RealOrangeOne** [comment] 2020-01-22 21:52
The final 2 kits will be collected tomorrow, and should be delivered Monday.

**Closed** 2020-03-05 08:51 UTC
Labels: A: Team Kits, I: Must Have, S: In Progress
