### ISSUE TITLE
Produce an updated Banner

### ISSUE THREAD

**Issue by mildlyincompetent** [srobo/tasks#89] opened 2019-02-13 18:27 UTC
We should make an updated banner for use at events and in group photos.

**Comment by Tyler-Ward** [comment] 2019-02-16 00:37
also see #90

**Comment by Tyler-Ward** [comment] 2019-02-26 19:58
Leadtime: 1 week

**Comment by Adimote** [comment] 2019-03-09 19:49
Antoine is assigned as it's a media thing, feel free to reassign

**Comment by PeterJCLaw** [comment] 2019-03-09 19:49
@antoinepetty would you be able to take this?

**Comment by antoinepetty** [comment] 2019-03-09 20:33
Sorry I'm not sure I'll be able to do this in the next couple of weeks. Is someone else more free?

**Comment by TomWheal** [comment] 2019-03-09 21:05
Im Happy to take this on is there an example?

**Comment by antoinepetty** [comment] 2019-03-09 21:30
I'm assuming it's referring to this: https://i.ytimg.com/vi/7pPs8UpPEEo/maxresdefault.jpg
Someone can correct me if I'm wrong but the changes required are:

- New Logo
- Sponsors are Motorola Foundation and University of Southampton

**Comment by TomWheal** [comment] 2019-03-09 23:07
I'm guessing this will suffice
![banner](https://user-images.githubusercontent.com/7452669/54078448-15e51700-42c0-11e9-84b4-57d070c56a18.png)

**Comment by RealOrangeOne** [comment] 2019-03-10 00:14
Design wise that looks great! I'm not sure how I feel about a solid white background? In my experience that's likely to fade very quickly, and will show dirt easily.

White on blue might look nice? Although that is exactly what we've just done for the t-shirts in #85

**Comment by TomWheal** [comment] 2019-03-10 10:57
Seeming this will cost and add more jobs in ordering it, alongside there not really being anywhere for it at susu, like there is at newbury. So maybe just a "frame" for photos. Something like this?

![PhotoBanner](https://user-images.githubusercontent.com/7452669/54084006-3befd300-4323-11e9-9d03-e9a1ce4acac1.png)

**Comment by RealOrangeOne** [comment] 2019-03-10 11:08
Considering the previous one was white, we can ignore my previous issues. 

The banner is still a 'nice to have', intentionally. The above 'frame' fits closer to #90 / #120 / #198 if anything

**Comment by TomWheal** [comment] 2019-03-10 11:40
Didn't see #90 ignore my last.

**Comment by PeterJCLaw** [comment] 2019-03-10 12:47
@TomWheal design looks good 👍, thanks.
I think the next step is to get some quotes, would you be able to do that?

**Comment by Tyler-Ward** [comment] 2019-03-10 23:14
They are around £25 pre vat (£30 with vat) for a 6ft by 2ft. how large do we want it to be.

http://www.indigo-press.com/packaged-print/printing/outdoor-banners/

**Comment by PeterJCLaw** [comment] 2019-03-11 08:25
I was expecting that we'd replace the existing one like-for-like. It's about 2' tall, but I'm not sure on the width.

**Comment by PeterJCLaw** [comment] 2019-03-11 08:28
Huh, it's taller than I thought: https://github.com/srobo/inventory/blob/aa93487a4e246b4ff5419c14a176a1c00260a17e/storage/banner-sr000#L5-L9

> A large (6m x 1m) vinyl banner that has the words "STUDENT ROBOTICS" on it along with the SR logo and the logos of the motorola foundation, ECS and BitBox.

**Comment by TomWheal** [comment] 2019-03-15 11:18
6mx1m

£84 inc VAT - Lead time 4-6 Days
https://vinylbannersprinting.co.uk/product/vinyl-banner-1-0-m-x-6-0-m/
£135 inc VAT - Lead Time ~1 Week
https://www.fastprint.co.uk/banner-printing/pvc-banners-and-vinyl-banners.html
£105 in VAT - Lead Time 4 Days
https://www.colourgraphics.com/pvc-banner-printing/
£142 in VAT - Lead TIme  ~1 Week
https://www.bannerbuzz.co.uk/vinyl-banners

If we want to go smaller it probably wouldn't make much of a difference

**Comment by PeterJCLaw** [comment] 2019-03-16 15:57
@TomWheal nice.

6m×1m is the size we currently have, so let's stick with that. The current one also has hemmed edges and eyelets, which we probably also want to have again; I think the quotes include that, but just for clarity/posterity.

Are there any particular considerations with any of these suppliers? For example, do they all support a suitably easy format for the drawings and colour-matching of the colours we want?

Was there a reason not to also quote from the site which Tyler linked (http://www.indigo-press.com/packaged-print/printing/outdoor-banners/)? They're in feet rather than meters, though I suspect that a 10' × 3' banner is probably close enough for this purpose and seems cheaper from them unless I'm missing something?

**Comment by TomWheal** [comment] 2019-03-16 16:28
They are all the same requirements and features as you mentioned, they don’t mention colour matching however as they’re the ‘budget’ suppliers (found some that were quoting £400+) I assume it’ll be fine. 

No particular reason for not including a quote from the one Tyler mentioned, apart from the fact I dislike places that don’t offer both imperial and metric options on their site... but if we’re happy with 10’ x3’ that’s an option. 

Also the quotes might change if we go for a standard size like 10x3’ most of the ones I got were custom 6x1m

**Comment by PeterJCLaw** [comment] 2019-03-16 16:42
Hrm, I'd assumed that 6m × 1m was effectively the same as 10' × 3', but of course it's not. Not sure what I was thinking. (6m × 1m would of course be 18' ×3').

Perhaps it's better to ask what the ratio we need for our logo plus sponsor logos is? Unless the price difference is ridiculously prohibitive (which it looks like it wouldn't be) I think it's more important to get a size which makes them look good than to use a standard size.

**Comment by TomWheal** [comment] 2019-03-18 09:50
The 6x1m works best for the logo + sponsors.
@Tyler-Ward whats the budget for this? I Suggest we maybe fit the banner to the budget, and try and get as close as we can.

**Comment by Tyler-Ward** [comment] 2019-03-18 09:58
we have a budget for branding material which has a fair amount left but also needs to cover other things as well.

**Comment by TomWheal** [comment] 2019-03-18 10:06
Another option is 3.5mx0.6m it's about the same ratio but a bit smaller and comes too £40 with shipping.
All I will change with the design is making it fit the new ratio. If we can decide on a size and place to order from this can be done by today

**Comment by Tyler-Ward** [comment] 2019-03-18 20:50
@TomWheal has designed a new banner which is now in https://github.com/srobo/promotional-material. 
Purchase has been approved for up to £85 for this.

**Comment by TomWheal** [comment] 2019-03-18 20:59
I’ve placed the order

**Comment by Tyler-Ward** [comment] 2019-03-18 21:18
have added to #200 for delivery tracking

**Comment by PeterJCLaw** [comment] 2019-03-18 22:22
@TomWheal not sure if there's time to adjust the design yet -- I've commented on https://github.com/srobo/promotional-material/pull/13 about the spacing being a bit squashed.

**Comment by TomWheal** [comment] 2019-03-19 11:02
@PeterJCLaw I phoned to try and adjust, unfortunately, the company we ordered with apparently works 24hs and had already started our printing by the time I saw your comment. The reason for the spacing either side is that the eyelets are placed every 50cm so having a 25cm space at each end would allow us to wrap the end of the banners around a pole to secure it without losing any details.

**Closed by TomWheal** 2019-03-19 11:02 UTC
Labels: design, should have, urgent
