### ISSUE TITLE
Audit inventory in Broom Cupboard

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#210] opened 2019-03-13 10:39 UTC
Lowish priority but we should audit the inventory in southampton as many things don't match between reality and the inventory. This should likely happen as part of the cupboard move to reduce effort required.

**Comment by trickeydan** [comment] 2019-05-01 22:01
When this occurs on Saturday, it'd be great if the checklist from the competition is updated to show things that were returned to the cupboard. Some items have been confirmed already.

**Comment by PeterJCLaw** [comment] 2019-05-01 22:05
For extra clarity -- this is an _if we have spare capacity_ on Saturday. I fully expect that we won't get around this as there's quite a lot of kit to get through and that's the priority.

**Comment by trickeydan** [comment] 2019-05-15 09:27
This was partially done, although I believe that some of the records have been lost. Thus we should still consider the state unknown imo.

**Comment by PeterJCLaw** [comment] 2019-08-20 23:05
@kierdavis @RealOrangeOne am I right in thinking that this effectively happened during the Smallpeice tidy-up?

**Comment by RealOrangeOne** [comment] 2019-08-21 08:31
Effectively, yes.

There is little to no SR kit in the broomcupboard, it should all live in the cupboards around the corner. 

Because that is an inventory location, everything was moved to it, meaning it should be up-to-date!

Looking at what's marked as being in the inventory now (https://github.com/srobo/inventory/tree/master/southampton/broomcupboard), I could definitely believe it to be accurate!

**Comment by trickeydan** [comment] 2019-08-21 10:16
It's worth noting that you removed equipment that we explicitly asked you not to remove.

You will have to discuss this after SRO's reform.

**Comment by kierdavis** [comment] 2019-08-21 21:03
It's pretty up to date, although there's still a few things to tidy up e.g. there's stuff recorded as being on the metal shelves which don't exist anymore, and I think the loose lipo bag made it back to Newbury.

**Comment by PeterJCLaw** [comment] 2019-09-08 20:26
@kierdavis if there are things which you know are different, would you be able to update the inventory for them? Alternatively are you suggesting that we need to do a full audit still?

**Comment by kierdavis** [comment] 2019-09-09 20:42
I don't think a full audit is needed but we should confirm where these items have ended up. I can move them to `unknown-location` in the meantime if you think that would be useful.

**Comment by PeterJCLaw** [comment] 2019-09-14 11:13
I'm assuming that they all went to wherever the new cupboard is? I'm not sure it's useful to move them elsewhere, though it might make sense to rename the directory if it has a new name?

Either way, I'm going to close this as I think the original intent has been completed.

**Closed by PeterJCLaw** 2019-09-14 11:13 UTC
Labels: I: Could Have

**Comment by joe9599** [comment] 2019-09-14 11:25
nothing has been moved to the new cupboard, so if it was in the old cupboard, it will still be there, we will hopefully be moving cupboard in the next month or so

**Comment by RealOrangeOne** [comment] 2019-09-14 13:27
Most of the SR kit is actually in the minibots cupboard, and the inventory updated to reflect that, so I think we're all good.

@joe9599 would be good to know once things have moved over to the new cupboard so the inventory can reflect reality! (Alternatively, having someone update the inventory as things are moved would be great!)
