### ISSUE TITLE
Plan how we will do extended kit loans to teams

### ISSUE THREAD

**Issue by Tyler-Ward** [srobo/tasks#186] opened 2019-02-24 22:55 UTC
We often let teams keep kit after the competition we should plan if and how we are going to do this.

**Comment by RealOrangeOne** [comment] 2019-03-01 13:19
Downgrading the urgency of this, as we should still be able to operate by enforcing teams return kit at the competition.

However, this is less than ideal, so we should still try to do this.

**Comment by Adimote** [comment] 2019-03-09 19:27
We need approval from trustees because it crosses SR years

**Comment by PeterJCLaw** [comment] 2019-03-10 15:20
From the description of the Core Team's [formation](https://srobo.gitbook.io/ops-manual/annual-robotics-competition/core-team#formation):
> At the end of the annual competition cycle, around early May, the Core Team is expected to meet with the Trustees to review the previous Competition Program. This serves as a useful event for both the Core Team to reflect on their achievements and the Trustees to gather as much information as possible to feed into the next competition cycle. After this meeting the Core Team is effectively disbanded.

Since the Core Team lasts until at least May, so we can trivially allow teams to keep their kits until about then.

Is this ticket about loans beyond that timescale?

**Comment by RealOrangeOne** [comment] 2019-03-10 19:18
No, loans for longer than a couple weeks are definitely out of scope! 

I agree that an extension until ~May should be ok to approve at the core-team level. I've added a section about this in the upcoming team email https://github.com/srobo/team-emails/pull/18

**Comment by RealOrangeOne** [comment] 2019-03-16 12:31
The above email has been sent.

We added an extension until 27th April, if teams let us know by 22nd March. The March deadline is also in the rules. Now that we've advertised this, i'm upgrading its status again.

The remaining tasks for this are to work out where to instruct teams to send kits for return, and enumerate those teams which need it, if necessary.

I'm happy that working on this on the setup days is still completely fine, or even after the competition, so moving its milestone too.

**Comment by PeterJCLaw** [comment] 2019-03-16 16:18
> The above email has been sent.

:+1: 

> The remaining tasks for this are to work out where to instruct teams to send kits for return, and enumerate those teams which need it, if necessary.

Likely either me at work or Southampton Uni are good addresses, with a preference for the latter (as most likely that's where the collation event will be) if there's someone there who's able to receive the items.

> I'm happy that working on this on the setup days is still completely fine, or even after the competition, so moving its milestone too.

Related to #115, we should work out how we'll confirm to teams that they can keep the kits longer and how we'll identify that at the competition. Having the person responsible for making the decision be at handback and/or a list on paper of the teams who have been given permission are viable options here.

We should also work out how these teams will get back a pair of batteries and a charger. We should cope with these items not being their original items, but do need a way to record which ones they take away (with the possibility that be done outside the inventory for later adjustment).

**Comment by RealOrangeOne** [comment] 2019-03-16 16:48
I'll ensure there's a public google sheet with this information on, so those at reception can see which schools have permission to take their kit, and can then log the batteries and charger they take with them.

**Comment by Tyler-Ward** [comment] 2019-03-16 20:18
> We should also work out how these teams will get back a pair of batteries and a charger. We should cope with these items not being their original items, but do need a way to record which ones they take away (with the possibility that be done outside the inventory for later adjustment).

It might be worth considering inventorying (or just recording the part codes of) the batteries and chargers we collect from teams after we have taken them from teams as we are now in charge of them, this will avoid any issues with teams who take kit away still begin marked as having other chargers as well.

**Comment by RealOrangeOne** [comment] 2019-03-16 20:33
I like the idea of this in theory, but we'd need someone who knows how to use the inventory to be available on both Saturday morning for when teams drop them off, and Sunday morning, for when teams being them bach from overnight.

I think ensuring teams get the same batteries back is unlikely to work well. If we want to manually inventory them, then this links closely to https://github.com/srobo/tasks/issues/121

**Comment by Tyler-Ward** [comment] 2019-03-16 20:48
We can avoid the need for someone trained in inventory use by just collecting the part numbers in a google sheet and inventorying them in bulk after teams have arrived. 

I can't see any way we could get teams the same parts back they came with without a lot of effort, not sure where that idea has come from.

**Comment by PeterJCLaw** [comment] 2019-03-16 21:45
I suspect it would be simpler to record the teams who, when the arrive, _don't_ give us all the components which we're taking off them. I'm only aware of one team which has had replacement battery related things, and I think they've still got the normal numbers of them.

This negative recording will most likely not have anything to record and we can sync the inventory at some point during the day rather than needing to worry about collecting part codes.

**Comment by RealOrangeOne** [comment] 2019-03-16 21:58
Discussion on how to do overnight loan to teams now has its own ticket https://github.com/srobo/tasks/issues/213.

Extending kit can be done by a volunteer at reception noting down the part numbers for the replaced items (batteries, charger) in a sheet when they leave. Volunteers can be instructed that those who haven't been given prior consent _must_ return their kit. 

With this list, we can modify the inventory after the fact.

**Comment by RealOrangeOne** [comment] 2019-03-22 22:00
For the return address, we will use the UKPostBox address listed at https://www.studentrobotics.org/contact/. There is a nominal charge (~£20 per kit).

The expenditure of this budget was approved by @Tyler-Ward in Slack (https://studentrobotics.slack.com/archives/GCRQS5D1P/p1553291378003000) to come from the kit replacement line.

**Comment by RealOrangeOne** [comment] 2019-03-23 10:50
The deadline has now passed, and only 1 team has requested a kit extension.

**Comment by RealOrangeOne** [comment] 2019-03-23 16:49
Due to specification of the deadline for the kit to be returned, said single team no longer require the kit extension, therefore we don't need to do this anymore.

I've already written the documentation, and it's correct, so we might as well keep that information around for future years.

**Comment by Tyler-Ward** [comment] 2019-03-23 23:00
I assume I am good to close off the budget for the extended loans then.

**Comment by RealOrangeOne** [comment] 2019-03-24 17:36
We have agreed to allow an extension to the extension deadline, therefore we will need to do this.

**Comment by PeterJCLaw** [comment] 2019-03-27 00:45
@RealOrangeOne I think this is planned now? Certainly the deadline for applications has passed and we have (I believe?) confirmed the one team who've asked.

**Comment by RealOrangeOne** [comment] 2019-03-27 09:37
Correct. We technically have a plan, although the relevant documents aren't quite finished. Most are ready for review on https://github.com/srobo/kit-coordination-docs, but I also need to address https://github.com/srobo/kit-coordination-documents/issues/8 before i'd be happy closing this.

**Comment by RealOrangeOne** [comment] 2019-04-02 12:01
https://github.com/srobo/kit-coordination-documents/issues/8 has now merged, so I'm happy to consider this done.

There's little documentation in the runbook on this, but the documents themselves cover most of it. I intend to update the runbook after the competition with the new processes etc from this year, when there's more time.

**Closed by RealOrangeOne** 2019-04-02 12:01 UTC
Labels: must have
